-- 32TechHub / ITEP Globe PostgreSQL foundation. Apply through Supabase MCP in a connected environment.
create extension if not exists pgcrypto;
create table if not exists public.profiles (id uuid primary key references auth.users(id) on delete cascade, role text not null default 'candidate', full_name text, headline text, bio text, locale text not null default 'en', country_code text, timezone text, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists public.companies (id uuid primary key default gen_random_uuid(), owner_id uuid references public.profiles(id) on delete set null, name text not null, slug text unique not null, description text, website text, country_code text, verified boolean not null default false, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists public.jobs (id uuid primary key default gen_random_uuid(), company_id uuid references public.companies(id) on delete cascade, title text not null, slug text unique not null, description text not null, location text, country_code text, work_mode text not null default 'onsite', employment_type text, salary_min numeric, salary_max numeric, currency text not null default 'USD', experience_level text, status text not null default 'draft', created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists public.services (id uuid primary key default gen_random_uuid(), provider_id uuid references public.profiles(id) on delete cascade, title text not null, slug text unique not null, description text not null, category text, price_from numeric, currency text not null default 'USD', status text not null default 'draft', created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists public.applications (id uuid primary key default gen_random_uuid(), job_id uuid references public.jobs(id) on delete cascade, candidate_id uuid references public.profiles(id) on delete cascade, status text not null default 'submitted', created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(job_id, candidate_id));
create table if not exists public.ai_matches (id uuid primary key default gen_random_uuid(), source_type text not null, source_id uuid not null, target_id uuid not null, score numeric not null, signals jsonb not null default '{}', created_at timestamptz not null default now());
create index if not exists jobs_status_created_idx on public.jobs(status, created_at desc); create index if not exists jobs_country_idx on public.jobs(country_code); create index if not exists applications_candidate_idx on public.applications(candidate_id, status); create index if not exists ai_matches_source_idx on public.ai_matches(source_type, source_id, score desc);
alter table public.profiles enable row level security; alter table public.companies enable row level security; alter table public.jobs enable row level security; alter table public.services enable row level security; alter table public.applications enable row level security; alter table public.ai_matches enable row level security;
create policy "published jobs are public" on public.jobs for select using (status = 'published' or exists (select 1 from public.companies c where c.id = company_id and c.owner_id = auth.uid()));
create policy "profiles are public" on public.profiles for select using (true);
create policy "users manage own profile" on public.profiles for update using (id = auth.uid()) with check (id = auth.uid());
create policy "candidates manage own applications" on public.applications for all using (candidate_id = auth.uid()) with check (candidate_id = auth.uid());
