'use client'

import { useMemo, useState } from 'react'
import Link from 'next/link'
import { ArrowUpRight, CheckCircle2, Layers3 } from 'lucide-react'
import { ecosystemCategories, ecosystemServices, type EcosystemCategory } from '@/lib/ecosystem'

export function EcosystemDirectory() {
  const [category, setCategory] = useState<(typeof ecosystemCategories)[number]>('All')
  const visible = useMemo(() => category === 'All' ? ecosystemServices : ecosystemServices.filter(service => service.category === category as EcosystemCategory), [category])
  return <section id="platform" className="border-y border-border bg-secondary/20"><div className="mx-auto max-w-7xl px-5 py-16 lg:px-8"><div className="grid gap-10 lg:grid-cols-[.7fr_1.3fr] lg:items-start"><div><p className="mb-3 text-xs font-bold uppercase tracking-[0.16em] text-accent-foreground">ITEP Globe / 32TechHub</p><h2 className="text-4xl font-semibold leading-tight tracking-[-0.04em]">One ecosystem.<br />Many ways forward.</h2><p className="mt-5 max-w-md leading-7 text-muted-foreground">A connected service layer for work, business, technology, community, and safety — designed to grow with every ITEP Globe module.</p><div className="mt-7 flex flex-wrap gap-2">{ecosystemCategories.map(item => <button key={item} onClick={() => setCategory(item)} className={`rounded-full border px-3 py-2 text-xs font-semibold transition ${category === item ? 'border-primary bg-primary text-primary-foreground' : 'border-border bg-card text-muted-foreground hover:text-foreground'}`}>{item}</button>)}</div></div><div className="grid gap-3 sm:grid-cols-2">{visible.map(service => <article key={service.id} className="rounded-2xl border border-border bg-card p-5 transition hover:-translate-y-0.5 hover:shadow-md"><div className="flex items-start justify-between gap-3"><span className="grid size-10 place-items-center rounded-xl bg-secondary text-secondary-foreground"><Layers3 className="size-4" /></span><span className="text-xs font-semibold text-muted-foreground">{service.category}</span></div><h3 className="mt-5 text-lg font-semibold tracking-tight">{service.name}</h3><p className="mt-2 text-sm leading-6 text-muted-foreground">{service.description}</p><div className="mt-4 flex flex-col gap-2">{service.functions.map(fn => <span key={fn} className="flex items-center gap-2 text-xs text-muted-foreground"><CheckCircle2 className="size-3.5 text-accent-foreground" />{fn}</span>)}</div><div className="mt-5 flex items-center justify-between border-t border-border pt-4"><span className="text-xs text-muted-foreground">{service.audience}</span><Link href={service.href} className="rounded-full p-1 text-foreground" aria-label={`Open ${service.name}`}><ArrowUpRight className="size-4" /></Link></div></article>)}</div></div></div></section>
}
