'use client'

import { useState } from 'react'
import { Ambulance, Flame, MapPin, Phone, ShieldAlert } from 'lucide-react'
import { emergencyNumbers } from '@/lib/trust-safety'

export function EmergencyAssistance() {
  const [location, setLocation] = useState<{ lat: number; lng: number } | null>(null)
  const [shared, setShared] = useState(false)
  const numbers = emergencyNumbers.DEFAULT
  const requestLocation = () => navigator.geolocation?.getCurrentPosition(position => { setLocation({ lat: position.coords.latitude, lng: position.coords.longitude }); setShared(true) }, () => setShared(false))
  return <section id="emergency" className="bg-primary text-primary-foreground"><div className="mx-auto max-w-7xl px-5 py-14 lg:px-8"><div className="grid gap-8 lg:grid-cols-[1fr_1.2fr] lg:items-center"><div><div className="flex items-center gap-2 text-xs font-bold uppercase tracking-[0.16em] opacity-70"><ShieldAlert className="size-4" /> Immediate assistance</div><h2 className="mt-4 text-3xl font-semibold tracking-tight">Need urgent help?</h2><p className="mt-3 max-w-lg leading-7 opacity-80">Call local emergency services immediately. 32TechHub supplements official dispatch and does not replace police, fire rescue, or ambulance services.</p><button onClick={requestLocation} className="mt-6 inline-flex items-center gap-2 rounded-lg bg-primary-foreground px-4 py-3 text-sm font-semibold text-primary">{shared ? <><MapPin className="size-4" /> Location ready to share</> : <><MapPin className="size-4" /> Share location with consent</>}</button>{location && <p className="mt-3 text-xs opacity-70">Location captured for an in-app incident report.</p>}</div><div className="grid gap-3 sm:grid-cols-3"><a href={`tel:${numbers.police}`} className="rounded-2xl border border-primary-foreground/20 bg-primary-foreground/10 p-5 transition hover:bg-primary-foreground/15"><ShieldAlert className="size-5" /><p className="mt-5 font-semibold">Police</p><p className="mt-1 flex items-center gap-1 text-sm opacity-75"><Phone className="size-3.5" /> {numbers.police}</p></a><a href={`tel:${numbers.fire}`} className="rounded-2xl border border-primary-foreground/20 bg-primary-foreground/10 p-5 transition hover:bg-primary-foreground/15"><Flame className="size-5" /><p className="mt-5 font-semibold">Fire rescue</p><p className="mt-1 flex items-center gap-1 text-sm opacity-75"><Phone className="size-3.5" /> {numbers.fire}</p></a><a href={`tel:${numbers.ambulance}`} className="rounded-2xl border border-primary-foreground/20 bg-primary-foreground/10 p-5 transition hover:bg-primary-foreground/15"><Ambulance className="size-5" /><p className="mt-5 font-semibold">Ambulance</p><p className="mt-1 flex items-center gap-1 text-sm opacity-75"><Phone className="size-3.5" /> {numbers.ambulance}</p></a></div></div></div></section>
}
