'use client'

import { useState } from 'react'
import { ArrowUpRight, Bell, CheckCircle2, Leaf, Mail, Scale, ShieldCheck } from 'lucide-react'

const sections = [
  { id: 'about', title: 'About 32TechHub', text: 'A facilitator connecting people, employers, property, services, projects, and trusted opportunities across the GCC and the world.' },
  { id: 'mission', title: 'Mission & vision', text: 'Make useful opportunities easier to discover, safer to evaluate, and faster to act on—while supporting inclusive growth and practical community impact.' },
  { id: 'privacy', title: 'Privacy & consumer health privacy', text: 'We minimize sensitive data, explain why information is requested, and treat health-related information as especially sensitive. Never share medical details unless necessary and authorized.' },
  { id: 'terms', title: 'Terms of use & legal', text: '32TechHub facilitates matching, referrals, information, and communication. It does not guarantee jobs, wages, property condition, payment, safety, or outcomes. Final terms are agreed by the relevant parties.' },
  { id: 'safety', title: 'Safety, eco & recycling', text: 'Report fraud, exploitation, cyber incidents, or unsafe content. Choose reusable, repairable, and responsibly recycled options when using marketplace services.' },
  { id: 'ads', title: 'About our ads', text: 'Sponsored placements should be labeled clearly. Advertising does not change verification status, search eligibility, or editorial decisions.' },
  { id: 'partners', title: 'Partner with us', text: 'Employers, service providers, ministries, NGOs, investors, and community organizers can propose verified programs, data feeds, and impact partnerships.' },
  { id: 'ecosystem', title: 'Our ecosystem', text: 'Jobs, talent, properties, services, campaigns, projects, payments, community, trust, releases, help, rights, and public-service support in one connected place.' },
  { id: 'domains', title: 'Trademarks, domains & legal notices', text: '32TechHub and related names, marks, domains, and service identities belong to their respective owners. Use of the platform does not transfer intellectual-property rights.' },
  { id: 'sitemap', title: 'Site map', text: 'Explore Jobs, Services, Properties, Projects, Community, Releases, Trust Center, Help Center, Rights, Payments, and Emergency Assistance from the main navigation.' },
]

export function InformationCenter() {
  const [subscribed, setSubscribed] = useState(false)
  return <section id="information" className="border-t border-border bg-secondary/30"><div className="mx-auto max-w-7xl px-5 py-16 lg:px-8"><div className="flex flex-col justify-between gap-5 md:flex-row md:items-end"><div><p className="mb-3 text-xs font-bold uppercase tracking-[0.16em] text-primary">Information & trust</p><h2 className="max-w-2xl text-4xl font-semibold leading-tight tracking-[-0.04em] text-foreground">Clear information for confident participation.</h2></div><p className="max-w-sm text-sm leading-6 text-muted-foreground">These pages are informational and do not replace professional legal, medical, financial, or emergency advice.</p></div><div className="mt-10 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{sections.map(item => <a key={item.id} id={item.id} href={`#${item.id}`} className="group rounded-2xl border border-border bg-card p-5 transition hover:border-primary/50"><div className="flex items-start justify-between gap-4"><h3 className="font-semibold text-foreground">{item.title}</h3><ArrowUpRight className="size-4 text-muted-foreground transition group-hover:text-primary" /></div><p className="mt-3 text-sm leading-6 text-muted-foreground">{item.text}</p></a>)}</div><div id="newsletter" className="mt-5 grid gap-5 rounded-2xl bg-primary p-6 text-primary-foreground md:grid-cols-[1fr_auto] md:items-center"><div><div className="flex items-center gap-2"><Bell className="size-4" /><p className="text-sm font-semibold">32TechHub bulletin & newsletter</p></div><p className="mt-2 max-w-xl text-sm leading-6 opacity-75">Get verified platform updates, useful releases, community campaigns, and public notices. Do not use this channel for emergencies.</p></div>{subscribed ? <div className="flex items-center gap-2 text-sm font-semibold"><CheckCircle2 className="size-4" /> Subscription request received</div> : <button onClick={() => setSubscribed(true)} className="inline-flex items-center justify-center gap-2 rounded-xl bg-primary-foreground px-4 py-3 text-sm font-semibold text-primary"><Mail className="size-4" /> Join bulletin</button>}</div><div className="mt-5 flex flex-wrap gap-3 text-xs text-muted-foreground"><span className="inline-flex items-center gap-1"><ShieldCheck className="size-3.5" /> Safety reporting</span><span className="inline-flex items-center gap-1"><Scale className="size-3.5" /> Legal review recommended</span><span className="inline-flex items-center gap-1"><Leaf className="size-3.5" /> Responsible marketplace</span></div></div></section>
}
