'use client'

import { useMemo, useState } from 'react'
import { CheckCircle2, CreditCard, Globe2, LockKeyhole, WalletCards } from 'lucide-react'
import { getPaymentMethods, paymentUseCases } from '@/lib/payments'

export function PaymentOptions() {
  const [market, setMarket] = useState('Saudi Arabia')
  const methods = useMemo(() => getPaymentMethods(market), [market])
  return <section id="payments" className="border-y border-border bg-secondary/30"><div className="mx-auto max-w-7xl px-5 py-16 lg:px-8"><div className="flex flex-col gap-8 lg:flex-row lg:items-end lg:justify-between"><div><p className="mb-2 text-xs font-bold uppercase tracking-[0.16em] text-accent-foreground">Pay your way</p><h2 className="max-w-2xl text-3xl font-semibold tracking-tight">Regional first. Global by design.</h2><p className="mt-3 max-w-xl text-sm leading-6 text-muted-foreground">Choose the market to see the payment rails we can prioritize. Ready methods are active through Stripe; local methods remain clearly marked until merchant onboarding is complete.</p></div><label className="flex items-center gap-2 rounded-xl border border-border bg-card px-3 py-2 text-sm"><Globe2 className="size-4 text-muted-foreground" /><span className="sr-only">Payment market</span><select value={market} onChange={event => setMarket(event.target.value)} className="bg-transparent font-semibold outline-none"><option>Saudi Arabia</option><option>United Arab Emirates</option><option>Kuwait</option><option>Qatar</option><option>Bahrain</option><option>Oman</option><option>Global</option></select></label></div><div className="mt-8 flex flex-wrap gap-2">{paymentUseCases.map(use => <span key={use} className="rounded-full border border-border bg-card px-3 py-2 text-xs font-medium">{use}</span>)}</div><div className="mt-6 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{methods.map(method => <article key={method.id} className="rounded-2xl border border-border bg-card p-5"><div className="flex items-center justify-between"><div className="flex items-center gap-2"><span className="grid size-9 place-items-center rounded-xl bg-secondary"><WalletCards className="size-4" /></span><h3 className="font-semibold">{method.name}</h3></div><span className={`rounded-full px-2 py-1 text-[10px] font-bold uppercase ${method.status === 'ready' ? 'bg-primary text-primary-foreground' : 'bg-secondary text-muted-foreground'}`}>{method.status === 'ready' ? 'Ready' : 'Adapter'}</span></div><p className="mt-4 text-xs text-muted-foreground">{method.market} · {method.currencies.join(', ')}</p><p className="mt-2 text-sm leading-6 text-muted-foreground">{method.note}</p><div className="mt-4 flex items-center gap-1.5 text-xs font-semibold"><CheckCircle2 className="size-3.5 text-accent-foreground" />{method.uses.join(' · ')}</div></article>)}</div><div className="mt-6 flex items-center gap-2 text-xs text-muted-foreground"><LockKeyhole className="size-3.5" /> Prices are validated server-side. Payment availability depends on customer location, currency, provider approval, and merchant configuration.</div></div></section>
}
