'use client'

import { useState } from 'react'
import { AlertTriangle, CheckCircle2, FileCheck2, Flag, ShieldCheck } from 'lucide-react'
import { verificationPrinciples } from '@/lib/trust-safety'

export function TrustCenter() {
  const [reported, setReported] = useState(false)
  return <section id="trust" className="border-y border-border bg-secondary/30"><div className="mx-auto max-w-7xl px-5 py-16 lg:px-8"><div className="grid gap-10 lg:grid-cols-[.8fr_1.2fr] lg:items-start"><div><p className="mb-3 text-xs font-bold uppercase tracking-[0.16em] text-accent-foreground">Trust by design</p><h2 className="text-4xl font-semibold leading-tight tracking-[-0.04em]">Double-check every opportunity.</h2><p className="mt-5 max-w-md leading-7 text-muted-foreground">Automated signals and trained reviewers work together to protect candidates, employers, and service providers from fake accounts and misleading jobs.</p><div className="mt-7 flex flex-col gap-3">{verificationPrinciples.map((item, index) => <div key={item} className="flex items-center gap-3 text-sm"><span className="grid size-7 place-items-center rounded-full bg-card text-xs font-bold">{index + 1}</span>{item}</div>)}</div></div><div className="grid gap-3 sm:grid-cols-2"><article className="rounded-2xl border border-border bg-card p-5"><CheckCircle2 className="size-5 text-accent-foreground" /><h3 className="mt-5 font-semibold">Verified employer</h3><p className="mt-2 text-sm leading-6 text-muted-foreground">Business identity, domain, recruiter role, and job details reviewed before publishing.</p><span className="mt-5 inline-flex items-center gap-1.5 rounded-full bg-secondary px-2.5 py-1 text-xs font-semibold"><ShieldCheck className="size-3.5" /> Double checked</span></article><article className="rounded-2xl border border-border bg-card p-5"><FileCheck2 className="size-5 text-accent-foreground" /><h3 className="mt-5 font-semibold">Report and appeal</h3><p className="mt-2 text-sm leading-6 text-muted-foreground">Flag an employer, worker, job, or service. Reports enter a tracked moderation queue.</p><button onClick={() => setReported(true)} className="mt-5 inline-flex items-center gap-2 rounded-lg border border-border px-3 py-2 text-sm font-semibold"><Flag className="size-4" />{reported ? 'Report received' : 'Report an issue'}</button></article></div></div></div></section>
}
